### ISSUE TITLE
Limit the retry mechanism.

### ISSUE THREAD

**Issue by leonprou** [fuseio/fuse-bridge#33]
The sender (`sender-home` and `sender-foreign`) containers have an infinite retry loop on failures.
For example if the user doesn't have enough ETH in his account the sender will retry until the account will have ETH. This is waste resources and API limits (like infura).

Need to:
- setup a limit for the retries (will be configured in the env)
- find other places in code when the same mechanics takes place. and where it's important to fix. for example collected-signature container is a possible candidate

**Comment by Andrew-Pohl** [comment]
Happy to look at this if needed @leonprou ?

**Comment by leonprou** [comment]
Sure, thanks @Andrew-Pohl!
Would be interesting to onboard you into the bridge codebase 😄

**Comment by Andrew-Pohl** [comment]
As mentioned to Leon this never ending loop was due to an error in the logic which checks for if a transaction has failed due to low eth (can't pay fees). If a node is low on eth it should close the relay queue and sit and wait for the eth to be topped up before retrying. 

Fix here https://github.com/fuseio/fuse-bridge/pull/34

**Comment by Andrew-Pohl** [comment]
Fixed and merged at commit 882fd27903a960c329535adb9dd42895bc0eb694
